apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: axpo-exercise-storage_api:latest
          imagePullPolicy: Never
          ports:
           - containerPort: 5000
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 200m