apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    app: storage
spec:
  type: ClusterIP
  selector:
    app: storage
  ports:
    - name: web
      protocol: TCP
      port: 5000
      targetPort: 5000


  