apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: storage
  labels:
    app: storage
spec:
  jobLabel: storege_api
  endpoints:
  - interval: 10s
    port: web
    path: /metrics  
  selector:
    matchLabels:
      app: storage